"""Read-only cyber event readiness precheck."""

from __future__ import annotations

import csv
import json
import logging
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from gecko_analytics_engine.config.settings import AppSettings
from gecko_analytics_engine.db.connection import DatabaseConnectionError, database_connection
from gecko_analytics_engine.db.reads import (
    count_rows,
    get_table_columns,
    safe_fetch_all,
    safe_scalar,
    table_exists,
)
from gecko_analytics_engine.db.schema_contract import (
    CYBER_EVENT_DATES,
    CYBER_EVENT_FEATURES,
    CYBER_EVENT_ID,
    CYBER_EVENT_IMPACTS,
    CYBER_EVENT_SECURITIES,
    CYBER_EVENT_SOURCES,
    CYBER_EVENTS,
    DATE_TYPE,
    DJI_DAILY_PRICES,
    EVENT_DATE,
    INDEX_DAILY_PRICES,
    IS_TRADING_DAY,
    MARKET_CALENDAR,
    MARKET_INDEXES,
    OUTPUT_TABLES,
    READINESS_VIEWS,
    SECURITY_DAILY_PRICES,
    SECURITY_ID,
    TRADE_DATE,
)
from gecko_analytics_engine.utils.paths import AppPaths


@dataclass(frozen=True)
class ReadinessMetric:
    """One event-readiness metric."""

    category: str
    name: str
    value: int | str | None
    status: str
    detail: str = ""


@dataclass(frozen=True)
class ReadinessBlocker:
    """A blocker or warning generated by the readiness precheck."""

    severity: str
    message: str


@dataclass(frozen=True)
class EventReadinessPrecheck:
    """Read-only event-readiness precheck result."""

    generated_at: str
    connection_ok: bool
    readiness_status: str
    database_name: str | None = None
    metrics: tuple[ReadinessMetric, ...] = ()
    blockers: tuple[ReadinessBlocker, ...] = ()
    export_paths: tuple[Path, ...] = ()
    error_message: str | None = None


def run_event_readiness_precheck(
    settings: AppSettings,
    paths: AppPaths,
    logger: logging.Logger | None = None,
) -> EventReadinessPrecheck:
    """Run and export the read-only event-readiness precheck."""

    generated_at = datetime.now(UTC).isoformat()

    try:
        with database_connection(settings) as connection:
            database_name = _selected_database(connection) or settings.db.name
            metrics = _collect_readiness_metrics(connection)
    except DatabaseConnectionError as exc:
        result = EventReadinessPrecheck(
            generated_at=generated_at,
            connection_ok=False,
            readiness_status="BLOCKED",
            error_message=str(exc),
        )
        _log_precheck(result, logger)
        return result
    except Exception as exc:
        result = EventReadinessPrecheck(
            generated_at=generated_at,
            connection_ok=False,
            readiness_status="BLOCKED",
            error_message=f"Event readiness precheck failed: {exc.__class__.__name__}: {exc}",
        )
        _log_precheck(result, logger)
        return result

    blockers = build_readiness_blockers(metrics)
    readiness_status = determine_readiness_status(blockers)
    result = EventReadinessPrecheck(
        generated_at=generated_at,
        connection_ok=True,
        readiness_status=readiness_status,
        database_name=database_name,
        metrics=metrics,
        blockers=blockers,
    )
    result = export_event_readiness_precheck(result, paths, logger)
    _log_precheck(result, logger)
    return result


def export_event_readiness_precheck(
    result: EventReadinessPrecheck,
    paths: AppPaths,
    logger: logging.Logger | None = None,
) -> EventReadinessPrecheck:
    """Export precheck artifacts when the database check completed."""

    if not result.connection_ok:
        return result

    paths.exports_dir.mkdir(parents=True, exist_ok=True)
    paths.reports_dir.mkdir(parents=True, exist_ok=True)

    json_path = paths.reports_dir / "event_readiness_precheck.json"
    summary_csv = paths.exports_dir / "event_readiness_precheck_summary.csv"
    blockers_csv = paths.exports_dir / "event_readiness_blockers.csv"
    export_paths = (json_path, summary_csv, blockers_csv)
    result_with_exports = _copy_precheck_with_export_paths(result, export_paths)

    _write_summary_csv(summary_csv, result.metrics)
    _write_blockers_csv(blockers_csv, result.blockers)
    _write_precheck_json(json_path, result_with_exports)

    if logger is not None:
        logger.info(
            "Event readiness precheck exports written: %s",
            ", ".join(str(path) for path in export_paths),
        )

    return result_with_exports


def format_event_readiness_precheck(result: EventReadinessPrecheck) -> list[str]:
    """Format a precheck result for console output."""

    lines = ["", "Cyber Event Readiness Precheck", "-------------------------------"]
    if not result.connection_ok:
        lines.extend(
            [
                "Overall status: BLOCKED",
                "Connection: FAILED",
                f"Reason: {result.error_message}",
            ]
        )
        return lines

    lines.extend(
        [
            f"Overall status: {result.readiness_status}",
            "Connection: OK",
            f"Database: {result.database_name or 'Unknown'}",
            f"Generated: {result.generated_at}",
            "",
            "Key counts and checks:",
        ]
    )

    for metric in result.metrics:
        value = _format_value(metric.value)
        detail = f" ({metric.detail})" if metric.detail else ""
        lines.append(f"  [{metric.status}] {metric.category} - {metric.name}: {value}{detail}")

    lines.extend(["", "Blockers / warnings:"])
    if result.blockers:
        for blocker in result.blockers:
            lines.append(f"  [{blocker.severity}] {blocker.message}")
    else:
        lines.append("  No blockers detected by this precheck.")

    if result.export_paths:
        lines.extend(["", "Exports:"])
        for path in result.export_paths:
            lines.append(f"  {path}")

    return lines


def print_event_readiness_precheck(result: EventReadinessPrecheck) -> None:
    """Print a precheck result to the console."""

    for line in format_event_readiness_precheck(result):
        print(line)


def determine_readiness_status(blockers: tuple[ReadinessBlocker, ...]) -> str:
    """Determine the overall readiness status from blockers and warnings."""

    if any(blocker.severity == "BLOCKER" for blocker in blockers):
        return "BLOCKED"
    if blockers:
        return "PARTIAL"
    return "READY_FOR_WINDOW_VALIDATION"


def build_readiness_blockers(
    metrics: tuple[ReadinessMetric, ...],
) -> tuple[ReadinessBlocker, ...]:
    """Generate readiness blockers and warnings from metrics."""

    values = {(metric.category, metric.name): metric for metric in metrics}
    blockers: list[ReadinessBlocker] = []

    _add_if_missing_or_unavailable(
        blockers,
        values,
        ("event counts", "total cyber events"),
        "cyber_events is unavailable.",
    )
    _add_if_missing_or_unavailable(
        blockers,
        values,
        ("event date readiness", "events with at least one date row"),
        "event date rows are unavailable.",
    )
    _add_if_missing_or_unavailable(
        blockers,
        values,
        ("security linkage readiness", "linked events"),
        "event/security links are unavailable.",
    )

    no_date_metric = values.get(("event date readiness", "events missing date rows"))
    if _positive_metric(no_date_metric):
        blockers.append(
            ReadinessBlocker(
                "WARNING",
                f"{no_date_metric.value} events are missing date rows.",
            )
        )

    no_link_metric = values.get(("security linkage readiness", "events with no linked security"))
    if _positive_metric(no_link_metric):
        blockers.append(
            ReadinessBlocker(
                "WARNING",
                f"{no_link_metric.value} events are missing security links.",
            )
        )

    no_price_metric = values.get(("price coverage readiness", "linked securities with no price rows"))
    if _positive_metric(no_price_metric):
        blockers.append(
            ReadinessBlocker(
                "WARNING",
                f"{no_price_metric.value} linked securities have no price rows.",
            )
        )

    source_metric = values.get(("event counts", "total cyber event sources"))
    if source_metric and source_metric.value == 0:
        blockers.append(ReadinessBlocker("WARNING", "cyber_event_sources is empty."))

    dji_metric = values.get(("index/benchmark readiness", "dji_daily_prices rows"))
    if dji_metric and dji_metric.value == 0:
        blockers.append(ReadinessBlocker("WARNING", "dji_daily_prices is empty."))

    index_price_metric = values.get(("index/benchmark readiness", "index_daily_prices rows"))
    if index_price_metric and isinstance(index_price_metric.value, int) and index_price_metric.value > 0:
        blockers.append(
            ReadinessBlocker(
                "WARNING",
                "Benchmark coverage appears to be in index_daily_prices; verify benchmark selection.",
            )
        )

    for table_name in ("event_study_runs", "event_study_results", "statistical_test_results"):
        metric = values.get(("analytics output tables", f"{table_name} rows"))
        if metric and metric.value == 0:
            blockers.append(
                ReadinessBlocker(
                    "INFO",
                    f"{table_name} is empty, expected before analytics outputs are generated.",
                )
            )

    return tuple(blockers)


def _collect_readiness_metrics(connection: Any) -> tuple[ReadinessMetric, ...]:
    metrics: list[ReadinessMetric] = []
    metrics.extend(_event_count_metrics(connection))
    metrics.extend(_event_date_metrics(connection))
    metrics.extend(_security_linkage_metrics(connection))
    metrics.extend(_price_coverage_metrics(connection))
    metrics.extend(_benchmark_metrics(connection))
    metrics.extend(_market_calendar_metrics(connection))
    metrics.extend(_readiness_view_metrics(connection))
    metrics.extend(_analytics_output_metrics(connection))
    return tuple(metrics)


def _event_count_metrics(connection: Any) -> list[ReadinessMetric]:
    table_labels = (
        ("total cyber events", CYBER_EVENTS),
        ("total event date rows", CYBER_EVENT_DATES),
        ("total event/security links", CYBER_EVENT_SECURITIES),
        ("total event feature rows", CYBER_EVENT_FEATURES),
        ("total event impact rows", CYBER_EVENT_IMPACTS),
        ("total cyber event sources", CYBER_EVENT_SOURCES),
    )
    return [
        _table_count_metric(connection, "event counts", label, table_name)
        for label, table_name in table_labels
    ]


def _event_date_metrics(connection: Any) -> list[ReadinessMetric]:
    table_name = CYBER_EVENT_DATES
    category = "event date readiness"
    if not table_exists(connection, table_name):
        return [_missing_metric(category, "events with at least one date row", table_name)]

    columns = set(get_table_columns(connection, table_name))
    metrics: list[ReadinessMetric] = []
    if {CYBER_EVENT_ID, EVENT_DATE}.issubset(columns):
        dated_events = safe_scalar(
            connection,
            f"SELECT COUNT(DISTINCT {CYBER_EVENT_ID}) FROM {CYBER_EVENT_DATES}",
        )
        metrics.append(_scalar_metric(category, "events with at least one date row", dated_events))
        total_events = count_rows(connection, CYBER_EVENTS)
        if isinstance(total_events, int) and isinstance(dated_events, int):
            metrics.append(
                ReadinessMetric(
                    category,
                    "events missing date rows",
                    max(total_events - dated_events, 0),
                    "OK" if total_events == dated_events else "WARNING",
                )
            )
        min_max = safe_scalar(
            connection,
            f"SELECT CONCAT(MIN({EVENT_DATE}), ' to ', MAX({EVENT_DATE})) FROM {CYBER_EVENT_DATES}",
        )
        metrics.append(_text_metric(category, "event date range", min_max, f"column={EVENT_DATE}"))
        metrics.append(
            ReadinessMetric(
                category,
                "usable for event day / disclosure day selection",
                "yes" if DATE_TYPE in columns else "partial",
                "OK" if DATE_TYPE in columns else "WARNING",
                "requires cyber_event_id, event_date, and preferably date_type",
            )
        )
    else:
        metrics.append(_unavailable_metric(category, "events with at least one date row", "missing cyber_event_id/event_date"))
        metrics.append(
            ReadinessMetric(
                category,
                "usable for event day / disclosure day selection",
                "no",
                "UNAVAILABLE",
                "missing cyber_event_id/event_date",
            )
        )

    if DATE_TYPE in columns:
        disclosure_events = safe_scalar(
            connection,
            """
            SELECT COUNT(DISTINCT cyber_event_id)
            FROM cyber_event_dates
            WHERE date_type IN ('disclosure', 'regulatory_filing', 'first_trading_day')
            """,
        )
        metrics.append(
            _scalar_metric(
                category,
                "events with disclosure/announcement-like dates",
                disclosure_events,
                "date_type in disclosure/regulatory_filing/first_trading_day",
            )
        )
        for date_type, count in safe_fetch_all(
            connection,
            """
            SELECT date_type, COUNT(*)
            FROM cyber_event_dates
            GROUP BY date_type
            ORDER BY date_type
            """,
        ):
            metrics.append(
                _scalar_metric(
                    category,
                    f"date type distribution: {date_type}",
                    count,
                )
            )
    else:
        metrics.append(_unavailable_metric(category, "date type distribution", "missing date_type column"))

    return metrics


def _security_linkage_metrics(connection: Any) -> list[ReadinessMetric]:
    table_name = CYBER_EVENT_SECURITIES
    category = "security linkage readiness"
    if not table_exists(connection, table_name):
        return [_missing_metric(category, "linked events", table_name)]

    columns = set(get_table_columns(connection, table_name))
    metrics: list[ReadinessMetric] = []
    if CYBER_EVENT_ID in columns:
        linked_events = safe_scalar(
            connection,
            f"SELECT COUNT(DISTINCT {CYBER_EVENT_ID}) FROM {CYBER_EVENT_SECURITIES}",
        )
        metrics.append(_scalar_metric(category, "linked events", linked_events))
        total_events = count_rows(connection, CYBER_EVENTS)
        if isinstance(total_events, int) and isinstance(linked_events, int):
            missing_links = max(total_events - linked_events, 0)
            metrics.append(
                ReadinessMetric(
                    category,
                    "events with no linked security",
                    missing_links,
                    "OK" if missing_links == 0 else "WARNING",
                )
            )
        multiple_security_events = safe_scalar(
            connection,
            """
            SELECT COUNT(*)
            FROM (
                SELECT cyber_event_id
                FROM cyber_event_securities
                GROUP BY cyber_event_id
                HAVING COUNT(DISTINCT security_id) > 1
            ) linked_event_counts
            """,
        ) if SECURITY_ID in columns else None
        metrics.append(
            _scalar_metric(
                category,
                "events with multiple linked securities",
                multiple_security_events,
            )
        )
    else:
        metrics.append(_unavailable_metric(category, "linked events", "missing cyber_event_id column"))

    if SECURITY_ID in columns:
        linked_securities = safe_scalar(
            connection,
            f"SELECT COUNT(DISTINCT {SECURITY_ID}) FROM {CYBER_EVENT_SECURITIES}",
        )
        metrics.append(_scalar_metric(category, "linked securities", linked_securities))
        metrics.append(_scalar_metric(category, "securities linked to cyber events", linked_securities))
        if CYBER_EVENT_ID in columns:
            duplicate_links = safe_scalar(
                connection,
                """
                SELECT COUNT(*)
                FROM (
                    SELECT cyber_event_id, security_id, COUNT(*) AS link_count
                    FROM cyber_event_securities
                    GROUP BY cyber_event_id, security_id
                    HAVING COUNT(*) > 1
                ) duplicate_links
                """,
            )
            metrics.append(_scalar_metric(category, "duplicate event/security link pairs", duplicate_links))
    else:
        metrics.append(_unavailable_metric(category, "linked securities", "missing security_id column"))

    return metrics


def _price_coverage_metrics(connection: Any) -> list[ReadinessMetric]:
    table_name = SECURITY_DAILY_PRICES
    category = "price coverage readiness"
    if not table_exists(connection, table_name):
        return [_missing_metric(category, "securities with at least one price row", table_name)]

    columns = set(get_table_columns(connection, table_name))
    metrics: list[ReadinessMetric] = [
        _table_count_metric(connection, category, "total security price rows", table_name)
    ]
    if SECURITY_ID in columns:
        securities_with_prices = safe_scalar(
            connection,
            f"SELECT COUNT(DISTINCT {SECURITY_ID}) FROM {SECURITY_DAILY_PRICES}",
        )
        metrics.append(
            _scalar_metric(category, "securities with at least one price row", securities_with_prices)
        )

        if table_exists(connection, CYBER_EVENT_SECURITIES) and SECURITY_ID in set(
            get_table_columns(connection, CYBER_EVENT_SECURITIES)
        ):
            linked_with_prices = safe_scalar(
                connection,
                """
                SELECT COUNT(DISTINCT ces.security_id)
                FROM cyber_event_securities ces
                INNER JOIN security_daily_prices sdp ON sdp.security_id = ces.security_id
                """,
            )
            linked_without_prices = safe_scalar(
                connection,
                """
                SELECT COUNT(DISTINCT ces.security_id)
                FROM cyber_event_securities ces
                LEFT JOIN security_daily_prices sdp ON sdp.security_id = ces.security_id
                WHERE sdp.security_id IS NULL
                """,
            )
            metrics.append(_scalar_metric(category, "linked securities with price rows", linked_with_prices))
            metrics.append(
                _scalar_metric(
                    category,
                    "linked securities with no price rows",
                    linked_without_prices,
                    "join cyber_event_securities to security_daily_prices",
                )
            )
    else:
        metrics.append(_unavailable_metric(category, "securities with at least one price row", "missing security_id column"))

    if TRADE_DATE in columns:
        trade_range = safe_scalar(
            connection,
            f"SELECT CONCAT(MIN({TRADE_DATE}), ' to ', MAX({TRADE_DATE})) FROM {SECURITY_DAILY_PRICES}",
        )
        metrics.append(_text_metric(category, "security price trade-date range", trade_range, f"column={TRADE_DATE}"))
    else:
        metrics.append(_unavailable_metric(category, "security price trade-date range", "missing trade_date column"))

    return metrics


def _benchmark_metrics(connection: Any) -> list[ReadinessMetric]:
    category = "index/benchmark readiness"
    metrics = [
        _table_count_metric(connection, category, "market indexes", MARKET_INDEXES),
        _table_count_metric(connection, category, "index_daily_prices rows", INDEX_DAILY_PRICES),
        _table_count_metric(connection, category, "dji_daily_prices rows", DJI_DAILY_PRICES),
    ]

    metrics.append(
        _date_range_metric(
            connection,
            category,
            "index trade-date range",
            INDEX_DAILY_PRICES,
            TRADE_DATE,
        )
    )
    metrics.append(
        _date_range_metric(
            connection,
            category,
            "DJIA-specific trade-date range",
            DJI_DAILY_PRICES,
            TRADE_DATE,
        )
    )

    index_rows = count_rows(connection, INDEX_DAILY_PRICES)
    dji_rows = count_rows(connection, DJI_DAILY_PRICES)
    if index_rows and index_rows > 0:
        metrics.append(ReadinessMetric(category, "benchmark data appears in index_daily_prices", "yes", "WARNING"))
    if dji_rows == 0:
        metrics.append(ReadinessMetric(category, "DJIA-specific table empty", "yes", "WARNING"))

    return metrics


def _market_calendar_metrics(connection: Any) -> list[ReadinessMetric]:
    category = "market calendar readiness"
    table_name = MARKET_CALENDAR
    metrics = [_table_count_metric(connection, category, "market calendar rows", table_name)]
    if not table_exists(connection, table_name):
        return metrics

    columns = set(get_table_columns(connection, table_name))
    if "calendar_date" in columns:
        metrics.append(
            _date_range_metric(connection, category, "market calendar date range", table_name, "calendar_date")
        )
    else:
        metrics.append(_unavailable_metric(category, "market calendar date range", "missing calendar_date column"))

    indicator = _first_present(columns, (IS_TRADING_DAY, "trading_day", "is_open"))
    if indicator:
        metrics.append(ReadinessMetric(category, "trading-day indicator detected", "yes", "OK", f"column={indicator}"))
        metrics.append(
            ReadinessMetric(
                category,
                "suitable for non-trading-date alignment",
                "yes",
                "OK",
                f"calendar_date plus {indicator}",
            )
        )
    else:
        metrics.append(ReadinessMetric(category, "trading-day indicator detected", "no", "WARNING"))
        metrics.append(
            ReadinessMetric(
                category,
                "suitable for non-trading-date alignment",
                "partial",
                "WARNING",
                "missing trading-day indicator",
            )
        )

    return metrics


def _readiness_view_metrics(connection: Any) -> list[ReadinessMetric]:
    category = "existing readiness views"
    metrics: list[ReadinessMetric] = []
    for view_name in READINESS_VIEWS:
        if table_exists(connection, view_name):
            row_count = count_rows(connection, view_name)
            metrics.append(_scalar_metric(category, f"{view_name} rows", row_count))
        else:
            metrics.append(ReadinessMetric(category, f"{view_name} rows", None, "MISSING"))
    return metrics


def _analytics_output_metrics(connection: Any) -> list[ReadinessMetric]:
    category = "analytics output tables"
    return [
        _table_count_metric(connection, category, f"{table_name} rows", table_name)
        for table_name in OUTPUT_TABLES
    ]


def _table_count_metric(
    connection: Any,
    category: str,
    label: str,
    table_name: str,
) -> ReadinessMetric:
    if not table_exists(connection, table_name):
        return _missing_metric(category, label, table_name)
    row_count = count_rows(connection, table_name)
    if row_count is None:
        return _unavailable_metric(category, label, "row count unavailable")
    return ReadinessMetric(category, label, row_count, "EMPTY" if row_count == 0 else "OK")


def _date_range_metric(
    connection: Any,
    category: str,
    label: str,
    table_name: str,
    date_column: str,
) -> ReadinessMetric:
    if not table_exists(connection, table_name):
        return _missing_metric(category, label, table_name)
    if date_column not in set(get_table_columns(connection, table_name)):
        return _unavailable_metric(category, label, f"missing {date_column} column")
    value = safe_scalar(
        connection,
        f"SELECT CONCAT(MIN(`{date_column}`), ' to ', MAX(`{date_column}`)) FROM `{table_name}`",
    )
    return _text_metric(category, label, value, f"column={date_column}")


def _scalar_metric(
    category: str,
    label: str,
    value: Any,
    detail: str = "",
) -> ReadinessMetric:
    if value is None:
        return _unavailable_metric(category, label, detail or "query returned no value")
    value = int(value)
    return ReadinessMetric(category, label, value, "EMPTY" if value == 0 else "OK", detail)


def _text_metric(
    category: str,
    label: str,
    value: Any,
    detail: str = "",
) -> ReadinessMetric:
    if value is None:
        return _unavailable_metric(category, label, detail or "query returned no value")
    return ReadinessMetric(category, label, str(value), "OK", detail)


def _missing_metric(category: str, label: str, table_name: str) -> ReadinessMetric:
    return ReadinessMetric(category, label, None, "MISSING", f"{table_name} table not found")


def _unavailable_metric(category: str, label: str, detail: str) -> ReadinessMetric:
    return ReadinessMetric(category, label, None, "UNAVAILABLE", detail)


def _add_if_missing_or_unavailable(
    blockers: list[ReadinessBlocker],
    values: dict[tuple[str, str], ReadinessMetric],
    key: tuple[str, str],
    message: str,
) -> None:
    metric = values.get(key)
    if metric is None or metric.status in {"MISSING", "UNAVAILABLE"}:
        blockers.append(ReadinessBlocker("BLOCKER", message))


def _positive_metric(metric: ReadinessMetric | None) -> bool:
    return bool(metric and isinstance(metric.value, int) and metric.value > 0)


def _first_present(columns: set[str], candidates: tuple[str, ...]) -> str | None:
    for candidate in candidates:
        if candidate in columns:
            return candidate
    return None


def _selected_database(connection: Any) -> str | None:
    value = safe_scalar(connection, "SELECT DATABASE()")
    return str(value) if value else None


def _write_summary_csv(path: Path, metrics: tuple[ReadinessMetric, ...]) -> None:
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=("category", "name", "value", "status", "detail"),
        )
        writer.writeheader()
        for metric in metrics:
            writer.writerow(asdict(metric))


def _write_blockers_csv(path: Path, blockers: tuple[ReadinessBlocker, ...]) -> None:
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=("severity", "message"))
        writer.writeheader()
        for blocker in blockers:
            writer.writerow(asdict(blocker))


def _write_precheck_json(path: Path, result: EventReadinessPrecheck) -> None:
    payload = asdict(result)
    payload["export_paths"] = [str(path) for path in result.export_paths]
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _copy_precheck_with_export_paths(
    result: EventReadinessPrecheck,
    export_paths: tuple[Path, ...],
) -> EventReadinessPrecheck:
    return EventReadinessPrecheck(
        generated_at=result.generated_at,
        connection_ok=result.connection_ok,
        readiness_status=result.readiness_status,
        database_name=result.database_name,
        metrics=result.metrics,
        blockers=result.blockers,
        export_paths=export_paths,
        error_message=result.error_message,
    )


def _format_value(value: int | str | None) -> str:
    if value is None:
        return "Unavailable"
    if isinstance(value, int):
        return f"{value:,}"
    return value


def _log_precheck(
    result: EventReadinessPrecheck,
    logger: logging.Logger | None,
) -> None:
    if logger is None:
        return
    if not result.connection_ok:
        logger.warning("Event readiness precheck failed: %s", result.error_message)
        return
    logger.info(
        "Event readiness precheck completed: database=%s status=%s metrics=%s blockers=%s",
        result.database_name,
        result.readiness_status,
        len(result.metrics),
        len(result.blockers),
    )
